try:
    # Prefer the static file generated by setuptools_scm at build time.
    # `ncatbot/_version.py` will be written by setuptools_scm when building/releases.
    from ._version import __version__  # type: ignore
except Exception:
    # Fallback for editable installs / local development where _version.py may not exist.
    __version__ = "0+unknown"

# 核心导出 — 使用惰性导入避免循环依赖
# ncatbot.utils → ncatbot_legacy.__init__ → .core → event_bus → ncatbot.utils (循环)
_CORE_NAMES = {"BotClient", "EventBus", "NcatBotEvent", "EventType"}


def __getattr__(name):
    if name in _CORE_NAMES:
        from .core import BotClient, EventBus, NcatBotEvent, EventType

        _exports = {
            "BotClient": BotClient,
            "EventBus": EventBus,
            "NcatBotEvent": NcatBotEvent,
            "EventType": EventType,
        }
        globals().update(_exports)
        return _exports[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "__version__",
    "BotClient",
    "EventBus",
    "NcatBotEvent",
    "EventType",
]
